# Configuration for the build_runner package.
# We have removed the custom 'binary_builder' to eliminate all build issues.
targets:
  $default:
    builders:
      # The key here should match the name of the builder in the factory.
      nexus|gpu_shader_builder:
        enabled: true

builders:
  # A unique key for our builder.
  gpu_shader_builder:
    # The package that contains the builder.
    import: "package:nexus/builder.dart"
    # The function in the imported library that creates the builder.
    builder_factories: ["gpuShaderBuilder"]
    # The extension for the generated files.
    build_extensions: {".dart": [".g.dart"]}
    # What files to run on. We target files ending with '_gpu_system.dart'.
    build_to: source
    # Automatically run this builder when dependencies change.
    auto_apply: dependents
