name: nexus
description: A highly scalable, clean, and data-oriented framework for Flutter, inspired by ECS and powered by BLoC and GetIt.
version: 3.0.1
homepage: https://github.com/ShoghShahadat/Nexus
repository: https://github.com/ShoghShahadat/Nexus
issue_tracker: https://github.com/ShoghShahadat/Nexus/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  get_it: ^7.7.0
  meta: ^1.11.0
  collection: ^1.18.0
  go_router: ^16.2.0
  shared_preferences: ^2.2.3
  web: ^1.0.0
  dio: ^5.4.3+1
  socket_io_client: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  build_runner: ^2.7.0
  source_gen: ^3.0.0-dev
  build: ^3.0.2
  analyzer: ^8.1.1

dependency_overrides:
  analyzer: '8.1.1'
